yarnPath: .yarn/releases/yarn-3.2.3.cjs
nodeLinker: node-modules
nmMode: 'hardlinks-local'

npmRegistryServer: 'https://artifactory.csq.fr/api/npm/npm'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

logFilters:
  - code: 'YN0060'
    level: discard
